name: Pytest with Pycodestyle

on: [push, pull_request]

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  -name: Set up Python 3.1 #whatever version I have
  uses: actions/setup-python@v2
  with:
    python-version: '3.31'
  -name: Install depencies
  run: pip install -r requirements.txt
  -name: Test with pytest
  evn:
    MONGODB: ${{ secrets.MONGODB }}
    MONGODB_ID: ${{ secrets.MONGODB_ID }}
  run:
    pytest -v --pycodestyle